# Generated by Django 4.2.7 on 2023-11-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('image', models.ImageField(default='no_image.jpg', max_length=1000, upload_to='', verbose_name='Фотография категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('old_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая цена')),
                ('image', models.ImageField(default='no_image.jpg', max_length=1000, upload_to='', verbose_name='Фотография продукта')),
                ('image_2', models.ImageField(default='no_image.jpg', max_length=1000, upload_to='', verbose_name='Фотография продукта №2 (Другая расцветка или другой ракурс)')),
                ('image_3', models.ImageField(default='no_image.jpg', max_length=1000, upload_to='', verbose_name='Фотография продукта №3 (Другая расцветка или другой ракурс)')),
                ('image_4', models.ImageField(default='no_image.jpg', max_length=1000, upload_to='', verbose_name='Фотография продукта №4 (Другая расцветка или другой ракурс)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='products.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
